config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, only: [:index, :show, :update]
  end

  resources :things
  devise_for :users
  root to: 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :index, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :index it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new

    can :manage, User if user.has_ability? :modify_users
    can :read, Thing if user.has_ability? :read_things
    can :create, Thing if user.has_ability? :create_things
    can :update, Thing if user.has_ability? :modify_things
    can :destroy, Thing if user.has_ability? :delete_things
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  ABILITIES = %i{
    read_things
    create_things
    modify_things
    delete_things
    modify_users
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def has_ability?(ability)
    abilities.include?(ability)
  end

  # Parse out the abilities used based on the mask stored on the User
  def abilities
    ABILITIES.reject do |r|
      (abilities_mask & 2**ABILITIES.index(r)).zero?
    end
  end

  # Calculate the proper mask value when setting abilities from a single ability or array of abilities
  def abilities=(abilities)
    abilities = [*abilities].map { |r| r.to_sym }
    self.abilities_mask = (abilities & ABILITIES).map { |r| 2**ABILITIES.index(r) }.inject(0, :+)
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :user_params, only: :update
    before_action :authenticate_user!
    load_and_authorize_resource

    def index
      @users = User.all
    end

    def show
      @user = User.find params[:id]
    end

    def update
      @user = User.find params[:id]
      @user.abilities = params[:user][:abilities]

      if @user.save
        flash[:notice] = "Abilities updated!"
        redirect_to admin_user_path @user
      end
    end

    private

    def user_params
      params.require(:user).permit(abilities: [])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index

  load_and_authorize_resource
  skip_authorize_resource only: :index

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        if can? :read, @thing
          format.html { redirect_to @thing, notice: "#{@thing.name} was successfully created." }
          format.json { render :show, status: :created, location: @thing }
        else
          format.html { redirect_to things_path, notice: "#{@thing.name} was successfully created, but you aren't authorized to see it now." }
          format.json { render :index, status: :created, location: @thing }
        end
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        if can? :read, @thing
          format.html { redirect_to @thing, notice: "#{@thing.name} was successfully updated." }
          format.json { render :show, status: :created, location: @thing }
        else
          format.html { redirect_to things_path, notice: "#{@thing.name} was successfully updated, but for a truly Kafka-esque experience you aren't authorized to see it now, even though you just saw all the details of it." }
          format.json { render :index, status: :created, location: @thing }
        end
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: "#{@thing.name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/admin/users/_user.html.erb
<tr>
  <th><%= user.email %></th>
  <th><%= link_to "Manage permissions", admin_user_path(user) %></th>
</tr>

app/views/admin/users/index.html.erb
<h1>Manage your Users!</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<h1>Manage abilities for <%= @user.email %></h1>
<%= form_for @user, url: admin_user_path(@user) do |f| %>
  <% User::ABILITIES.each do |ability| %>
      <%= check_box_tag "user[abilities][#{ability}]", ability, @user.has_ability?(ability), name: "user[abilities][]" %>
      <%= label_tag "user_abilities_#{ability}", ability.to_s.humanize %><br />
  <% end %>
  <%= hidden_field_tag "user[abilities][]", "" %>

  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>User Management!</h1>
  <p>Hi there! Welcome to the place where you can manage users' access and control of things!</p>
</div>
<div class="container">
  <% if user_signed_in? %>
  <div class="col-md-6">
    <h2>Go look at some things!</h2>
    <%= link_to "Things!", things_path, class: "btn btn-default" %>
  </div>
  <% else %>
  <div class="col-md-6">
    <h2>New here?</h2>
    <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-default" %>
  </div>
  <div class="col-md-6">
    <h2>Been around before?</h2>
    <%= link_to "Sign in!", new_user_session_path, class: "btn btn-default" %>
  </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <%= link_to "User Management", root_path, class: "navbar-brand" %>
          </div>
          <div id="navbar">
            <ul class="nav navbar-nav">
              <li><%= link_to "Things", things_path %></li>
              <% if can? :manage, User %>
                <li><%= link_to "Manage Users", admin_users_path %></li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><p class="navbar-text">Signed in as <%= link_to current_user.email, edit_user_registration_path, class: "navbar-link" %></p></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_for(thing) do |f| %>
  <% if thing.errors.any? %>
    <div id="alert alert-danger">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>Things</h1>

<table class="table table-hover">
  <colgroup span="4">
    <col>
    <col span="3" style="width: 5%; text-align: center;">
  </colgroup>
  <thead>
    <tr>
      <th>Name</th>
      <% if can?(:read, Thing) || can?(:update, Thing) || can?(:destroy, Thing) %>
        <th colspan="3" class="action">Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <% if can? :read, thing %>
          <td class="action">
            <%= link_to 'Show', thing %>
          </td>
        <% end %>
        <% if can? :update, thing %>
          <td class="action">
            <%= link_to 'Edit', edit_thing_path(thing) %>
          </td>
        <% end %>
        <% if can? :destroy, thing %>
          <td class="action">
            <%= link_to 'Destroy', thing, method: :delete, data: { confirm: "Are you sure you want to destroy #{thing.name}?" } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing', new_thing_path if can? :create, Thing %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<% if can? :update, @thing %>
  <%= link_to 'Edit', edit_thing_path(@thing) %> |
<% end %>
<%= link_to 'Back', things_path %>